---
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
ignorePatterns:
  - 'dist/'
  - 'src/*.test.ts'
overrides:
  - files: ['*.ts', '*.tsx']
    extends:
      - plugin:@typescript-eslint/recommended
    parserOptions:
      project: ['tsconfig.json']
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
