---
name: version
on:
  pull_request:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Fail if version has not been updated
        if: steps.check.outputs.changed != 'true'
        run: exit 1

      - name: Install dependencies
        run: sudo apt-get install -y make

      - name: Run version check
        run: make version
